---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:15.0.2
  amd64: ghcr.io/hassio-addons/base-python/amd64:15.0.2
  armhf: ghcr.io/hassio-addons/base-python/armhf:15.0.2
  armv7: ghcr.io/hassio-addons/base-python/armv7:15.0.2
  i386: ghcr.io/hassio-addons/base-python/i386:15.0.2
codenotary:
  base_image: codenotary@frenck.dev
