---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:13.1.2
  amd64: ghcr.io/hassio-addons/base-python/amd64:13.1.2
  armhf: ghcr.io/hassio-addons/base-python/armhf:13.1.2
  armv7: ghcr.io/hassio-addons/base-python/armv7:13.1.2
  i386: ghcr.io/hassio-addons/base-python/i386:13.1.2
codenotary:
  base_image: codenotary@frenck.dev
